name: Python application

on:
  schedule:
    - cron: '0 8 * * *'  # Deze cron expressie betekent elke dag om 8:00 AM UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

<<<<<<< HEAD
    - name: Debug info
      run: |
        echo "Python version:"
        python --version
        echo "Pip version:"
        pip --version
        echo "Installed packages:"
        pip list

=======
>>>>>>> 917e61c075d2e3cf3456d99474ca2981f48e8900
    - name: Run script
      run: |
        python news_bot.py
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}

    - name: Check for errors
      if: failure()
      run: |
        echo "An error occurred. Please check the logs for more details."
