name: Update posted articles

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  update-posted-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot feedparser

      - name: Run script
        run: python news_bot.py

      - name: Check for changes
        run: git status

      - name: Commit and Push changes
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add posted_articles.json posted_articles_backup.json
          git commit -m "Update posted articles"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
